apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: 699702042074.dkr.ecr.us-east-1.amazonaws.com/dev-profile-service:latest
          ports:
            - containerPort: 8002
      restartPolicy: Always
